"Id","CaseNumber","Ticket_Record_Type_Name__c","Subject","Description","DevOps_Steps_to_Reproduce__c","What_We_Know__c","Next_Steps__c","Solution_Comment__c","Issue_Type__c","Ticket_Owner_Name__c","Ticket_Type__c","Platform__c","Collector_Code__c","Feature__c","Product_Version__c","Build_Number__c","Age__c","Status","Account_Name__c","Contact_Name__c","CreatedDate","ClosedDate"
"500Qk00000LJtW9IAL","00434312","Support Ticket","EntraIDInventory failing - ExecuteScalar requires an open and available Connection. The connection's current state is closed.","Full error:

30/01/2025 19:00:31	ERROR	AZUREADINVENTORY	Stealthbits.StealthAUDIT.DataCollectors.AzureADInventory.Tasks.AADInventoryScanTask.InternalProcessRecord	""System.InvalidOperationException: ExecuteScalar requires an open and available Connection. The connection's current state is closed.     at System.Data.SqlClient.SqlCommand.ValidateCommand(String method, Boolean async)     at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)     at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)     at System.Data.SqlClient.SqlCommand.ExecuteScalar()     at Stealthbits.StealthAUDIT.DataCollectors.AzureADInventory.Database.AADInventoryDatabaseUpdate.CalculateEffectiveGroupMembership(Action`1 taskStatus)     at Stealthbits.StealthAUDIT.DataCollectors.AzureADInventory.Database.AADInventoryDatabaseUpdate.FinalizeScan(Action`1 taskStatus)     at Stealthbits.StealthAUDIT.DataCollectors.AzureADInventory.Database.AADInventoryDatabaseUpdate.Finish(Action`1 taskStatus)     at Stealthbits.StealthAUDIT.DataCollectors.AzureADInventory.Tasks.AADInventoryScanTask.InternalProcessRecord()""	NYCDOE.ONMICROSOFT.COM	DCExtract	11052	8124	15696

Prior to these runs we were getting a UNIQUE key constraint so we dropped the data and then resscaned.  There was a successful run and then 3 runs with this error.  Seems to always happen after here:
28/01/2025 19:00:49	INFO	AZUREADINVENTORY	Stealthbits.StealthAUDIT.DataCollectors.AzureADInventory.Tasks.AADInventoryScanTask.InternalProcessRecord	""Begin effective group membership calculation""	NYCDOE.ONMICROSOFT.COM	DCExtract	14948	2756	11964

But it does look to be immediate not some time inbetween.  The timeout on the job is set to 1440 so def not that much time has passed.

I see another open case with the same issue: 00433160

Attaching logs for the past 4 runs (1 success and 3 failure)","","","","Appeared to be a resource issue related to performance when a back up started at same time as scan.
after moving scan it appears to behavie","Incorrect configuration: Netwrix server","Nicholas Zimmer","Unexpected Behavior","Netwrix Enterprise Auditor","StealthAUDIT for AzureAD","Data Collection","11.6","11.6.0.125","26.0","Closed - Resolved","New York City Department of Education","Luis Noboa","2025-01-31T16:32:20.000Z","2025-02-26T15:51:04.000Z"
