"Id","ParentId","Type","CreatedById","CreatedDate","Body","Title","LinkUrl","RelatedRecordId","InsertedById","LastModifiedDate"
"0D5Qk00000Y5rrWKAR","500Qk00000MUa7qIAD","TextPost","0054u000008ARZjAAO","2025-03-03T13:23:54.000Z","Description: hi there,
It appears that we are having some recent scan issues with the following jobs. Which is preventing other scan jobs father down the tree from starting, which might result in a loss of auditing data for us. The specific jobs that have been throwing errors are:

FileSystem Scan - SEEK System and Bulk Import jobs

I've attached a few snippets of the jobs here, and some of the errors in txt format below.. Happy to extract some job logs for review as well.. Thanks! Doug 

<a href='https://Stealthbits.StealthAUDIT.DataCollectors.FSAA' target='_blank'>Stealthbits.StealthAUDIT.DataCollectors.FSAA</a>.FSAAException: Failed to maintain SDD Tier 2 database PNVAWSOAPP2.OHPNY.COM_DLPEX.fsaadb: SQL logic error
no such table: DLPEX.version ---> <a href='https://System.Data' target='_blank'>System.Data</a>.SQLite.SQLiteException: SQL logic error
no such table: DLPEX.version
   at <a href='https://System.Data' target='_blank'>System.Data</a>.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at <a href='https://System.Data' target='_blank'>System.Data</a>.SQLite.SQLiteCommand.BuildNextCommand()
   at <a href='https://System.Data' target='_blank'>System.Data</a>.SQLite.SQLiteCommand.GetStatement(Int32 index)
   at <a href='https://System.Data' target='_blank'>System.Data</a>.SQLite.SQLiteDataReader.NextResult()
   at <a href='https://System.Data.SQLite.SQLiteDataReader..ctor' target='_blank'>System.Data.SQLite.SQLiteDataReader..ctor</a>(SQLiteCommand cmd, CommandBehavior behave)
   at <a href='https://System.Data' target='_blank'>System.Data</a>.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at <a href='https://System.Data' target='_blank'>System.Data</a>.SQLite.SQLiteCommand.ExecuteReader()
   at DLPStorageFileQueue.SqliteStorageMigration.GetDbVersion(SQLiteConnection connection, String alias)
   at DLPStorageFileQueue.SqliteStorageMigration.Migrate(SQLiteConnection connection, Action`1 logInfo, String alias)
   at <a href='https://Stealthbits.StealthAUDIT.DataCollectors.FSAA' target='_blank'>Stealthbits.StealthAUDIT.DataCollectors.FSAA</a>.Tier2.OpenTier2(String dbPath, String host, ScanType dbType, DatabaseFiles dbFiles)
   --- End of inner exception stack trace ---
   at <a href='https://Stealthbits.StealthAUDIT.DataCollectors.FSAA' target='_blank'>Stealthbits.StealthAUDIT.DataCollectors.FSAA</a>.Tier2.OpenTier2(String dbPath, String host, ScanType dbType, DatabaseFiles dbFiles)
   at <a href='https://Stealthbits.StealthAUDIT.DataCollectors.FSAA' target='_blank'>Stealthbits.StealthAUDIT.DataCollectors.FSAA</a>.BulkImportTask.InternalProcessRecord()
   at <a href='https://Stealthbits.StealthAUDIT.DataCollectors.Tasks.Task' target='_blank'>Stealthbits.StealthAUDIT.DataCollectors.Tasks.Task</a>.StartExecute()


------------------------------


code = Corrupt (11), message = <a href='https://System.Data' target='_blank'>System.Data</a>.SQLite.SQLiteException (0x800007EF): database disk image is malformed
database disk image is malformed
   at <a href='https://System.Data' target='_blank'>System.Data</a>.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at <a href='https://System.Data.SQLite.SQLite3.Step' target='_blank'>System.Data.SQLite.SQLite3.Step</a>(SQLiteStatement stmt)
   at <a href='https://System.Data' target='_blank'>System.Data</a>.SQLite.SQLiteDataReader.NextResult()
   at <a href='https://System.Data.SQLite.SQLiteDataReader..ctor' target='_blank'>System.Data.SQLite.SQLiteDataReader..ctor</a>(SQLiteCommand cmd, CommandBehavior behave)
   at <a href='https://System.Data' target='_blank'>System.Data</a>.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at <a href='https://System.Data' target='_blank'>System.Data</a>.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at <a href='https://System.Data' target='_blank'>System.Data</a>.SQLite.SQLiteCommand.ExecuteNonQuery()
   at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader)
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command)
   at Dapper.SqlMapper.Execute(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType)
   at <a href='https://Stealthbits.StealthAUDIT.DataCollectors.FSAA' target='_blank'>Stealthbits.StealthAUDIT.DataCollectors.FSAA</a>.Tier2.OpenTier2(String dbPath, String host, ScanType dbType, DatabaseFiles dbFiles)
   at <a href='https://Stealthbits.StealthAUDIT.DataCollectors.FSAA' target='_blank'>Stealthbits.StealthAUDIT.DataCollectors.FSAA</a>.BulkImportTask.InternalProcessRecord()
   at <a href='https://Stealthbits.StealthAUDIT.DataCollectors.Tasks.Task' target='_blank'>Stealthbits.StealthAUDIT.DataCollectors.Tasks.Task</a>.StartExecute()","","","","0054u000008ARZjAAO","2025-03-03T13:23:54.000Z"
"0D5Qk00000Y6FCIKA3","500Qk00000MUa7qIAD","TextPost","0054u000006gpoAAAQ","2025-03-03T14:31:27.000Z","<p>I believe this is the time to run a Reset Host from the FSAA MAintenance. </p><p>After the Reset Import. If that is all happy then run the scan and import again.</p><p> </p><p> </p>","","","","0054u000006gpoAAAQ","2025-03-03T14:31:27.000Z"
"0D5Qk00000Y6XE9KAN","500Qk00000MUa7qIAD","TextPost","00570000003KXurAAG","2025-03-03T16:02:43.000Z","What We've Learned Updated: No steps have been taking to resolve these issues. 
They appear to have started on or around 2/15 with sporadic results it seems. 
I can’t tell you what exactly is affecting in our reporting at the moment. 
I’ve asked our IT Risk team to provide feedback there. 
I will grab the latest full job export and status messages once I re-run the jobs shortly.","","","","00570000003KXurAAG","2025-03-03T16:02:43.000Z"
"0D5Qk00000YNWApKAP","500Qk00000MUa7qIAD","TextPost","00570000003KXurAAG","2025-03-05T16:34:14.000Z","<p>Possible relation to <b>Escalation Ticket Number 00400203</b> FSAA/FS_SEEK .net error crash Age 324.0 Days</p><p><a href=""https://nwxcorp.lightning.force.com/lightning/r/Case/500Qk000009JmweIAC/view?ws=%2Flightning%2Fr%2FCase%2F500Qk00000MUa7qIAD%2Fview"" alt=""https://nwxcorp.lightning.force.com/lightning/r/Case/500Qk000009JmweIAC/view?ws=%2Flightning%2Fr%2FCase%2F500Qk00000MUa7qIAD%2Fview"" target=""_blank"">https://nwxcorp.lightning.force.com/lightning/r/Case/500Qk000009JmweIAC/view?ws=%2Flightning%2Fr%2FCase%2F500Qk00000MUa7qIAD%2Fview</a></p>","","","","00570000003KXurAAG","2025-03-05T16:34:14.000Z"
"0D5Qk00000YPFv7KAH","500Qk00000MUa7qIAD","TextPost","00570000003KXurAAG","2025-03-05T21:44:10.000Z","Invitation updated. Attendees: Dusty Grayson, Douglas Kupcha","","","","00570000003KXurAAG","2025-03-05T21:44:10.000Z"
"0D5Qk00000YPFv5KAH","500Qk00000MUa7qIAD","TextPost","00570000003KXurAAG","2025-03-05T21:44:10.000Z","Invitation updated. Attendees: No attendees listed","","","","00570000003KXurAAG","2025-03-05T21:44:10.000Z"
"0D5Qk00000YPFv6KAH","500Qk00000MUa7qIAD","TextPost","00570000003KXurAAG","2025-03-05T21:44:10.000Z","Invitation updated. Attendees: Dusty Grayson","","","","00570000003KXurAAG","2025-03-05T21:44:10.000Z"
"0D5Qk00000Z5NlDKAV","500Qk00000MUa7qIAD","TextPost","00570000003KXurAAG","2025-03-12T20:22:43.000Z","Next Steps Updated: Awaiting Meeting 3/17/2025 1:00 PM","","","","00570000003KXurAAG","2025-03-12T20:22:43.000Z"
"0D5Qk00000Z5TLRKA3","500Qk00000MUa7qIAD","TextPost","00570000003KXurAAG","2025-03-12T20:24:16.000Z","Steps to Reproduce Updated: Root cause currently unknown","","","","00570000003KXurAAG","2025-03-12T20:24:16.000Z"
"0D5Qk00000am17GKAQ","500Qk00000MUa7qIAD","TextPost","00570000003KXurAAG","2025-03-31T22:40:41.000Z","<p>Host in question are scanned via <b>MSTask Task Scheduler </b>– Creates a scheduled task on the target host that runs the applet</p><p>Netwrix Enterprise Auditor v11.6 &gt; Administration &gt; Data Collectors &gt; FileSystemAccess Data Collector &gt; FSAA: Applet Settings</p><p><a href=""https://helpcenter.netwrix.com/bundle/EnterpriseAuditor_11.6/page/Content/EnterpriseAuditor/Admin/DataCollector/FSAA/AppletSettings.htm"" alt=""https://helpcenter.netwrix.com/bundle/EnterpriseAuditor_11.6/page/Content/EnterpriseAuditor/Admin/DataCollector/FSAA/AppletSettings.htm"" target=""_blank"">https://helpcenter.netwrix.com/bundle/EnterpriseAuditor_11.6/page/Content/EnterpriseAuditor/Admin/DataCollector/FSAA/AppletSettings.htm</a> </p><p> </p><p><b>Automatic </b>(Local for NAS device hosts, Remote for Windows hosts) – Applet is deployed to all targeted Windows servers. Other targeted devices, for example NAS, are scanned locally by the Enterprise Auditor Console server.</p><p>The scan identifies Windows servers through the host inventory field OSType</p><p>Netwrix Enterprise Auditor v11.6 &gt; Administration &gt; Data Collectors &gt; FileSystemAccess Data Collector &gt; <b>FSAA: Scan Server Selection</b></p><p><a href=""https://helpcenter.netwrix.com/bundle/EnterpriseAuditor_11.6/page/Content/EnterpriseAuditor/Admin/DataCollector/FSAA/ScanServerSelection.htm"" alt=""https://helpcenter.netwrix.com/bundle/EnterpriseAuditor_11.6/page/Content/EnterpriseAuditor/Admin/DataCollector/FSAA/ScanServerSelection.htm"" target=""_blank"">https://helpcenter.netwrix.com/bundle/EnterpriseAuditor_11.6/page/Content/EnterpriseAuditor/Admin/DataCollector/FSAA/ScanServerSelection.htm</a></p><p> </p><p>***00437497SA_Core_TS_03_27_2025_T-15140.CollectionGROUP_0.CollectionGROUP_1.PermissionsJOB_1-FSAA System ScansOUTPUT1-FSAA System Scans_Log.tsv</p><p> </p><p>25/03/2025 20:39:51 ERROR FILESYSTEMACCESS Stealthbits.StealthAUDIT.DataCollectors.Tasks.Task.StartExecute &quot;System.TimeoutException: Retry timeout exceeded ---&gt; System.Net.Http.HttpRequestException: An error occurred while sending the request. ---&gt; System.Net.WebException: Unable to connect to the remote server ---&gt; System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 10.192.64.46:8766   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket&amp; socket, IPAddress&amp; address, ConnectSocketState state, IAsyncResult asyncResult, Exception&amp; exception)   --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)   --- End of inner exception stack trace ---   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at Stealthbits.StealthAUDIT.DataCollectors.FSAA.Applet.Client.HttpsClient.&lt;SendRequestAsync&gt;d__33.MoveNext() --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at Stealthbits.StealthAUDIT.DataCollectors.FSAA.Applet.Client.HttpsClient.&lt;&lt;GetScanStatusAsync&gt;b__14_0&gt;d.MoveNext() --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at Stealthbits.StealthAUDIT.DataCollectors.FSAA.Applet.Client.HttpsClient.&lt;GetScanStatusAsync&gt;d__14.MoveNext() --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at Stealthbits.StealthAUDIT.DataCollectors.FSAA.Util.&lt;&gt;c__DisplayClass26_0`1.&lt;RetryTaskWithTimeLimit&gt;b__0()   at Stealthbits.StealthAUDIT.DataCollectors.FSAA.Util.RetryWithTimeLimit[TResult](TimeSpan timeLimit, TimeSpan retryDelay, Func`1 func, Log log, Func`2 shouldRetryFunc)   --- End of inner exception stack trace ---   at Stealthbits.StealthAUDIT.DataCollectors.FSAA.Util.RetryWithTimeLimit[TResult](TimeSpan timeLimit, TimeSpan retryDelay, Func`1 func, Log log, Func`2 shouldRetryFunc)   at Stealthbits.StealthAUDIT.DataCollectors.FSAA.Util.RetryTaskWithTimeLimit[TResult](TimeSpan timeLimit, TimeSpan retryDelay, Func`1 func, Log log, Func`2 shouldRetryFunc)   at Stealthbits.StealthAUDIT.DataCollectors.FSAA.ScanTaskBase.&lt;GetScanStatusAndVerifyCompletionAsync&gt;d__21.MoveNext() --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)   at Stealthbits.StealthAUDIT.DataCollectors.FSAA.AccessScanTask.&lt;InternalProcessRecordAsync&gt;d__2.MoveNext() --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()   at Stealthbits.StealthAUDIT.DataCollectors.FSAA.AccessScanTask.&lt;InternalProcessRecordAsync&gt;d__2.MoveNext() --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()   at Stealthbits.StealthAUDIT.DataCollectors.FSAA.AccessScanTask.&lt;InternalProcessRecordAsync&gt;d__2.MoveNext() --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at Stealthbits.StealthAUDIT.DataCollectors.FSAA.AccessScanTask.InternalProcessRecord()   at Stealthbits.StealthAUDIT.DataCollectors.Tasks.Task.StartExecu</p><p> </p><p><b>Possible Causes</b></p><p>Service Not Running: The Netwrix agent or service on the target machine isn’t running or isn’t listening on port 8766.</p><p>Firewall Blocking: A firewall on the target machine or network is preventing connections to port 8766.</p><p>Network Issue: There’s a connectivity problem between the NEA server and the target machine (e.g., routing issues, incorrect IP, etc.).</p><p>Configuration Error: The target machine’s IP or port settings in NEA might be misconfigured.</p><p>Server Overload/Rejection: The target machine might be overloaded or explicitly configured to refuse connections.</p><p> </p><p><b>Check Target Machine:</b></p><p>Verify that the Netwrix agent (if used) is installed and running on 10.192.64.46.</p><p>Ensure the service is listening on port 8766 (e.g., use netstat -an | find &quot;8766&quot; on Windows).</p><p>Test Connectivity:</p><p>From the NEA server, use tools like telnet 10.192.64.46 8766 or Test-NetConnection -ComputerName 10.192.64.46 -Port 8766 (PowerShell) to confirm the port is reachable.</p><p>Review NEA Configuration:</p><p>In the NEA management console, check the FSAA task settings to ensure the correct IP and port are specified for the target.</p><p>Firewall and Network:</p><p>Confirm that no firewall rules block traffic to 10.192.64.46:8766.</p><p>Validate network connectivity between the NEA server and the target.</p>","","","","00570000003KXurAAG","2025-03-31T22:40:41.000Z"
